defconfig: Add missing config CONFIG_PSI
ERROR: files are incompatible: Runtime info and framework compatibility matrix are incompatible: No compatible kernel requirement found (kernel FCM version = 5).
For kernel requirements at matrix level 5, Kernel config errors:
    Missing config CONFIG_PSI